services:
  postgres:
    container_name: postgres
    image: postgres:13.15
    environment:
      - POSTGRES_PASSWORD=resetplease
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jake
      - MONGO_INITDB_ROOT_PASSWORD=dancebaby
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/var/lib/mongodb/data"

volumes:
  pgdata: 
  mongodata:


